---
- name: loop3
  hosts: all
  vars:
    mail_services:
      - postfix
      - dovecot
  tasks:
    - name: postfix and services are running
      service:
        name: "{{ item }}"
        state: started
      with_items:
        "{{ mail_services }}"
